export default {

  /** STATUS CODE 2XX */
  OK: 'OK',
  CREATED: 'CREATED',
  ACCEPTED: 'ACCEPTED',
  NO_CONTENT: 'NO_CONTENT',
  /** */
  /** STATUS CODE 4XX */
  UNAUTHORIZED: 'UNAUTHORIZED',
  BAD_REQUEST: 'BAD_REQUEST',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',

  /** STATUS CODE 5XX */
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',

}